#!/bin/sh
find . -name '*.py' \
-o -name '*.java' \
-o -iname '*.[CH]' \
-o -name '*.cpp' \
-o -name '*.cc' \
-o -name '*.hpp'  \
> cscope.files

# -b: just build
# -q: create inverted index
if [ -f cscope.files ]; then
	cscope -b -q
	mv cscope.files .cscope.files
	mv cscope.out .cscope.out
	mv cscope.in.out .cscope.in.out
	mv cscope.po.out .cscope.po.out
fi
